### ISSUE TITLE
ビルドしようとするとエラーが出る

### ISSUE THREAD

**Issue by sakuyuki1341** [UECwings/steering_rl78#10]
@msawahara 
ビルドを試みると以下のようなエラーが発生し、ビルドすることができませんでした。
<details>
<summary>エラー内容</summary>
	F0011	　CC78K0R error F0011: Illegal path '-IFDLRL78 Type04\V1.05\incrl78' <br>
	F3006	　VF78K0R error F3006: File not found 'DefaultBuild\main.rel' <br>
	F3006	　VF78K0R error F3006: File not found 'DefaultBuild\FIFO.rel' <br>
	F3006	　VF78K0R error F3006: File not found 'DefaultBuild\Flash.rel' <br>
	F3006	　VF78K0R error F3006: File not found 'DefaultBuild\Servo.rel' <br>
	F3006	　VF78K0R error F3006: File not found 'DefaultBuild\SoftUART.rel'	<br>
	F3006	　VF78K0R error F3006: File not found 'DefaultBuild\UART0.rel' <br>
	F3006　 VF78K0R error F3006: File not found 'DefaultBuild\System.rel' <br>
	F3011	　VF78K0R error F3011: Illegal path '-iFDLRL78 TYPE04\V1.05\LIBRL78' <br>
</details>

**Comment by msawahara** [comment]
#7 でも少し触れましたが，ビルドするためにはRL78/G13 フラッシュ・データ・ライブラリ(FDLRL78 Type04)を別途用意し，プロジェクトフォルダ内にコピーする必要があります．
同梱しようかと思いましたが，再配布が可能なライセンスか確認をしていないため，今は同梱していません．

**Comment by sakuyuki1341** [comment]
了解です、有難う御座います

**Comment by sakuyuki1341** [comment]
ダウンロードしてパス周辺をいじったらビルドに成功しました！！
ご助言ありがとう御座います！！
