### ISSUE TITLE
IOピンの接続についてドキュメントに記載する

### ISSUE THREAD

**Issue by UECwings** [UECwings/steering_rl78#3]
IOピンの接続についてドキュメントに記載する．
とりあえずREADME.mdに書けば良さそう

**Comment by msawahara** [comment]
ソースを読む限り，以下の通りの接続になっているはず．
P1.6 = RxD0 (サーボ用)
P1.7 = TxD0 (サーボ用)
P2.2 = ANI2 (ジョイスティック入力)
P2.3 = ANI3 (ジョイスティック入力)
P3.0 = LED (Red)
P4.0 = 1-wire programmer 兼 デバッグ用シリアル通信ポート
P5.0 = LED (Green)
P5.1 = LED (Blue)
